AllCops:
  NewCops: enable
  TargetRubyVersion: 3.0
  DisplayCopNames: true
  Exclude:
    - 'bin/**/*'
    - 'config/**/*'
    - 'db/**/*'
    - 'Gemfile*'
    - 'script/**/*'
    - 'test/**/*'
    - 'vendor/**/*'
    - 'node_modules/**/*'

Style/Documentation:
  Enabled: false
Style/MethodDefParentheses:
  Enabled: false

Lint/MissingSuper:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/EmptyMethod:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Style/BlockDelimiters:
  Enabled: false

Style/FormatString:
  Enabled: false

Layout/LineLength:
  Max: 200
